(ns replique.main-js-test
  "Finding the main modules of a project again, and moving them to this
  process's port.

  A main module is written into an application's own assets - `replique.cljs'
  says why - and so it outlives every process that ever wrote it. The two
  servers listen on ephemeral ports, which makes the file stale the moment the
  process that wrote it stops: the page still includes it and it still names a
  port nobody is listening on.

  Replique 1 refreshed them from the editor. This process does it itself, when
  it starts a browser runtime, which is the first moment there is a port to
  refresh them to.

  Written for the process that has a ClojureScript compiler in it, as
  `replique.cljs-ops-test' is - `clojure -M:test:cljs'. Walking a project for
  files whose first line says what they are is not itself a question about
  ClojureScript, but what those files SAY is: a main module is what `main-js'
  writes, and what it writes for a namespace is the path that compiler emits
  for it. A fixture built by hand instead would be a fixture that could drift
  out of the shape the thing under test has to match.

  MOST OF IT NEEDS NO PROCESS, though. Only the four tests about when the
  refresh happens on its own start one."
  (:require [clojure.java.io :as io]
            [clojure.string :as string]
            [clojure.test :refer [deftest is testing]]
            [replique.cljs :as cljs]
            [replique.test-client :as client :refer [with-process]])
  (:import [java.io File StringWriter]
           [java.net URI]
           [java.nio.file Files]
           [java.nio.file.attribute FileAttribute]))

(defn- compiling? []
  (cljs/available?))

;;; Making one of each kind of file

(defn- stale!
  "A main module of this replique, naming URL, at PATH under DIR."
  ([dir path] (stale! dir path "http://localhost:9999/" "the.program"))
  ([dir path url main]
   (let [f (io/file dir path)]
     (io/make-parents f)
     (spit f (cljs/main-js url main))
     f)))

(defn- masters!
  "A main module of replique 1, which this one must not claim.

  Master matches its own by comparing that many characters of the first line,
  and the two markers are deliberately not prefixes of each other - a project
  where both repliques are used would otherwise have two of them quietly
  rewriting one file."
  [dir path]
  (let [f (io/file dir path)]
    (io/make-parents f)
    (spit f (str "//main-js-file autogenerated by replique\n"
                 "(function() {\n  var port = '51832';\n"
                 "  var host = 'localhost';\n  var mainNs = 'nosco.ewen';\n})();\n"))
    f))

(defn- ordinary!
  [dir path]
  (let [f (io/file dir path)]
    (io/make-parents f)
    (spit f "export const x = 1;\n")
    f))

(defn- port-of [text]
  (second (re-find #"(?m)^const port = \"([^\"]*)\";$" text)))

(defn- host-of [text]
  (second (re-find #"(?m)^const host = \"([^\"]*)\";$" text)))

;;; What the walk finds

(deftest test-a-main-module-is-recognised-by-its-first-line-and-by-nothing-else
  ;; BY THE FIRST LINE AND NOT BY A LIST KEPT SOMEWHERE, because the file
  ;; outlives the process that wrote it - that is the whole of what makes it go
  ;; stale - and a process started tomorrow has never heard of it.
  (when (compiling?)
    (let [dir (client/temp-dir)]
      (try
        (stale! dir "assets/js/main.js")
        (stale! dir "deep/deeper/deepest/other.js")
        (masters! dir "assets/js/replique-1.js")
        (ordinary! dir "assets/js/app.js")
        (spit (io/file dir "assets/js/notjs.txt") (cljs/main-js "http://x:1/" "a.b"))
        (let [found (cljs/main-js-files (io/file dir))]
          (is (= #{"main.js" "other.js"} (set (map #(.getName ^File %) found))))
          (testing "replique 1's file is not one of ours"
            ;; The markers are deliberately not prefixes of each other. Were this
            ;; to claim master's file it would rewrite it into a shape master
            ;; cannot read, in a project where both are used.
            (is (not-any? #(= "replique-1.js" (.getName ^File %)) found)))
          (testing "and neither is a file that merely contains one"
            (is (not-any? #(= "notjs.txt" (.getName ^File %)) found))))
        (finally (client/delete-recursively dir))))))

(deftest test-the-walk-does-not-go-where-a-project-keeps-what-is-not-its-own
  ;; A walk is the price of not being told where the files are, and these are
  ;; what keeps it from also being the price of starting a repl: .git is
  ;; enormous, node_modules is tens of thousands of .js files that this did not
  ;; write, and a symbolic link is how the walk of a project becomes the walk
  ;; of a disk.
  (when (compiling?)
    (let [dir       (client/temp-dir)
          elsewhere (client/temp-dir)]
      (try
        (stale! dir "src/main.js")
        (stale! dir ".git/hooks/main.js")
        (stale! dir "node_modules/some-package/main.js")
        (stale! dir "build/main.js")
        (spit (io/file dir "build" ".repliqueignore") "")
        (stale! elsewhere "linked/main.js")
        (Files/createSymbolicLink (.toPath (io/file dir "linked"))
                                  (.toPath (io/file elsewhere "linked"))
                                  (make-array FileAttribute 0))
        (let [found (cljs/main-js-files (io/file dir))]
          (is (= 1 (count found)) (pr-str (mapv str found)))
          (is (= (.getCanonicalPath (io/file dir "src" "main.js"))
                 (.getCanonicalPath ^File (first found))))
          (testing "and the ignored ones are still there, merely not walked into"
            (is (.isFile (io/file dir "build" "main.js")))))
        (finally (client/delete-recursively dir)
                 (client/delete-recursively elsewhere))))))

;;; What a refresh writes

(deftest test-a-refresh-moves-the-host-and-the-port-and-leaves-the-program-alone
  ;; THE HOST AND THE PORT AND NOTHING ELSE, which is what master rewrote as
  ;; well. `mainNs' and `mainPath' say what the PAGE loads, and that is the
  ;; choice of whoever wrote the page rather than of whichever repl happens to
  ;; be running now.
  (when (compiling?)
    (let [dir (client/temp-dir)]
      (try
        (let [f    (stale! dir "assets/main.js" "http://localhost:9999/" "the.program")
              was  (slurp f)
              done (cljs/refresh-main-js! dir "http://127.0.0.1:41234/")
              now  (slurp f)]
          (is (= 1 (count done)))
          (is (true? (:refreshed (first done))))
          (testing "the port and the host are this process's"
            (is (= "41234" (port-of now)))
            (is (= "127.0.0.1" (host-of now))))
          (testing "and they were somebody else's before"
            (is (= "9999" (port-of was)))
            (is (= "localhost" (host-of was))))
          (testing "the program the page loads is untouched"
            (is (re-find #"(?m)^const mainNs = \"the\.program\";$" now) now)
            (is (re-find #"(?m)^const mainPath = \"ns/the/program\.js\";$" now) now))
          (testing "and so is everything that is not one of those two lines"
            (is (= (remove #(or (string/starts-with? % "const host")
                                (string/starts-with? % "const port"))
                           (string/split-lines was))
                   (remove #(or (string/starts-with? % "const host")
                                (string/starts-with? % "const port"))
                           (string/split-lines now)))))
          (testing "so the file is still one of ours"
            (is (seq (cljs/main-js-files (io/file dir))))))
        (finally (client/delete-recursively dir))))))

(deftest test-what-a-refresh-found-is-what-an-editor-would-offer
  ;; An editor that found these files learns from them which namespaces this
  ;; project can be started on - master harvested them in the same pass and
  ;; showed them in a completing-read. Nothing asks for it yet, and it costs a
  ;; key to carry it out of a walk already done.
  (when (compiling?)
    (let [dir (client/temp-dir)]
      (try
        (stale! dir "a/main.js" "http://localhost:1/" "my.app")
        (stale! dir "b/main.js" "http://localhost:2/" "my.other")
        (stale! dir "c/main.js" "http://localhost:3/" nil)
        (let [done (cljs/refresh-main-js! dir "http://127.0.0.1:7/")]
          (is (= 3 (count done)))
          (is (= #{"my.app" "my.other"} (set (keep :main done))))
          (testing "a module naming no program says so rather than being left out"
            ;; A repl in a page of yours with no program in it is a thing to
            ;; want, and the page still has to connect.
            (is (= 3 (count (distinct (map :file done)))))
            (is (= 1 (count (filter (comp nil? :main) done))))))
        (finally (client/delete-recursively dir))))))

(deftest test-a-module-already-naming-this-port-is-not-written-again
  ;; A file whose modification time means something to somebody's build, and a
  ;; refresh that touched all of them every time would be a rebuild nobody
  ;; asked for.
  (when (compiling?)
    (let [dir (client/temp-dir)]
      (try
        (let [f (stale! dir "main.js" "http://127.0.0.1:41234/" "the.program")]
          (.setLastModified f 1000000)
          (let [done (cljs/refresh-main-js! dir "http://127.0.0.1:41234/")]
            (is (= 1 (count done)))
            (is (false? (:refreshed (first done))))
            (testing "and it says what the module names all the same"
              (is (= "the.program" (:main (first done)))))
            (testing "the file was not written"
              (is (= 1000000 (.lastModified f))))))
        (finally (client/delete-recursively dir))))))

(deftest test-a-module-that-cannot-be-written-does-not-stop-the-others
  ;; ONE FILE FAILING IS NOT THE WALK FAILING - a main module somebody made
  ;; read only is a thing that happens.
  (when (compiling?)
    (let [dir (client/temp-dir)
          err (StringWriter.)]
      (try
        (let [locked (stale! dir "locked/main.js")
              open   (stale! dir "open/main.js")]
          (.setWritable locked false)
          (let [done (binding [*err* err]
                       (cljs/refresh-main-js! dir "http://127.0.0.1:41234/"))]
            (testing "the one that could be written was"
              (is (= "41234" (port-of (slurp open)))))
            (testing "the one that could not was left as it was"
              (is (= "9999" (port-of (slurp locked)))))
            (testing "and it was reported rather than thrown"
              (is (string/includes? (str err) "locked"))
              (is (string/includes? (str err) "Could not refresh")))
            (testing "the walk answered for both, and said which one it moved"
              (is (= 2 (count done)))
              (is (= 1 (count (filter :refreshed done)))))
            (testing "and the one it could not move carries why, and still its program"
              ;; A module that could not be rewritten is still a module naming a
              ;; namespace this project can be started on, and the menu that is
              ;; for has nothing to do with whether the port moved.
              (let [bad (first (filter :error done))]
                (is (string/includes? (:file bad) "locked"))
                (is (= "the.program" (:main bad)))
                (is (false? (:refreshed bad)))))))
        (finally (.setWritable (io/file dir "locked" "main.js") true)
                 (client/delete-recursively dir))))))

;;; The wiring: when it happens on its own

(deftest test-starting-a-browser-runtime-refreshes-the-project-s-main-modules
  (when (compiling?)
    ;; NOT WHEN THE PROCESS STARTS, which is when master's editor did it,
    ;; because there is no port until the two servers are listening and they
    ;; are not started until something asks. A refresh any earlier would write
    ;; a port nobody serves.
    (with-process [info]
      (let [f    (stale! (:directory info) "assets/main.js")
            said (with-out-str
                   (binding [cljs/*target* :browser] (cljs/runtime!)))
            url  (binding [cljs/*target* :browser] (:url (cljs/runtime!)))
            now  (slurp f)]
        (testing "the module names the port this process is serving"
          (is (= (str (.getPort (URI. url))) (port-of now)))
          (is (= (.getHost (URI. url)) (host-of now))))
        (testing "and it was said, once, to whoever started the repl"
          ;; Said only where something changed: a project with no main modules
          ;; in it is most projects, and a walk that announced itself every
          ;; time would be noise on every repl that ever starts.
          (is (string/includes? said "1 main module refreshed"))
          (is (string/includes? said url)))
        (testing "a second ask does not start a second runtime, so nothing is said again"
          (let [again (with-out-str
                        (binding [cljs/*target* :browser] (cljs/runtime!)))]
            (is (= "" again))))))))

(deftest test-a-project-with-no-main-modules-in-it-says-nothing
  (when (compiling?)
    ;; Which is most projects. A walk that announced itself every time would be
    ;; a line of noise on every browser repl that ever starts, about a thing
    ;; the person starting it has never asked for.
    (with-process [_]
      (let [err  (StringWriter.)
            said (binding [*err* err]
                   (with-out-str
                     (binding [cljs/*target* :browser] (cljs/runtime!))))]
        (is (= "" said))
        (is (= "" (str err)))))))

(deftest test-a-node-runtime-refreshes-nothing
  (when (compiling?)
    ;; The main module is the browser's alone: it is what a PAGE includes in
    ;; order to be the runtime, and node is a process this starts. A node repl
    ;; in a project has no business rewriting the files a page loads - the port
    ;; it would write is not even the one those servers listen on.
    (with-process [info]
      (let [f    (stale! (:directory info) "assets/main.js")
            err  (StringWriter.)
            said (binding [*err* err]
                   (with-out-str
                     (binding [cljs/*target* :node] (cljs/runtime!))))]
        (is (= "9999" (port-of (slurp f))))
        (is (= "" said))
        (testing "and it did not try and fail, which is a different nothing"
          ;; A node runtime is a process this started rather than a pair of
          ;; servers, so it has no url to refresh anything to. A refresh that
          ;; ran here would therefore not quietly do nothing - it would
          ;; complain, on every node repl that ever starts.
          (is (not (string/includes? (str err) "main module")) (str err)))))))

(deftest test-a-module-written-by-a-previous-process-is-moved-to-this-one
  (when (compiling?)
    ;; THE WHOLE STORY, end to end and across a restart. A client asks for a
    ;; main module once, into its application's own assets, and never thinks
    ;; about it again; every process after that finds the file and points it at
    ;; itself. Yesterday's port is why this exists - the two servers are
    ;; ephemeral, so the file is stale the moment the process that wrote it
    ;; stops.
    (let [dir (client/temp-dir)
          f   (io/file dir "assets" "main.js")]
      (try
        (let [wrote (with-process [info {:directory dir}]
                      ;; A relative :file is relative to the process's
                      ;; :directory, which is the one the walk will root at
                      (let [c (client/control-client info)]
                        (try (client/request! c {:op :main-js :id 1
                                                 :file "assets/main.js"
                                                 :main "the.program"})
                             (finally (client/disconnect c)))))
              stale (slurp f)]
          (is (= "reply" (:tag wrote)) (pr-str wrote))
          (is (= (str (.getPort (URI. (str (:url wrote))))) (port-of stale)))

          (with-process [_ {:directory dir}]
            (let [said (with-out-str
                         (binding [cljs/*target* :browser] (cljs/runtime!)))
                  url  (binding [cljs/*target* :browser] (:url (cljs/runtime!)))
                  now  (slurp f)]
              (testing "the module names this process, not the one that wrote it"
                (is (= (str (.getPort (URI. url))) (port-of now)))
                (is (string/includes? said "1 main module refreshed")))
              (testing "and the program it loads is still the one that was asked for"
                ;; Which repl is running is not what decides what the page
                ;; loads - that was settled when the file was written.
                (is (re-find #"(?m)^const mainNs = \"the\.program\";$" now) now)
                (is (re-find #"(?m)^const mainPath = \"ns/the/program\.js\";$" now)
                    now)))))
        (finally (client/delete-recursively dir))))))
